- recipes-commercial/mx4-utils/mx4-utils_git.bb
The service was not enabled at all without this fix.
Signed-off-by: Mirza Krak <mirza@mkrak.org>
> mx4-utils: fix typo in SYSTEMD_SERVICE

- conf/machine/include/mx5-base.inc
- conf/machine/mx5-pt.conf
- recipes-bsp/u-boot/u-boot-mobilityx-2019.04/0001-Add-target-to-generate-initial-environment.patch
- recipes-bsp/u-boot/u-boot-mobilityx_2019.04.bb
- recipes-kernel/linux/linux-mobilityx/0001-Compiler-Attributes-add-support-for-__copy-gcc-9.patch
- recipes-kernel/linux/linux-mobilityx/0001-perf-Make-perf-able-to-build-with-latest-libbfd.patch
- recipes-kernel/linux/linux-mobilityx/0002-include-linux-module.h-copy-__init-__exit-attrs-to-i.patch
- recipes-kernel/linux/linux-mobilityx_4.19.bb
- wic/hm-mx5-uboot.wks.in
Build and tested with console-hostmobility-image. No protocol
like CAN has been tested, just a diff between poky dunfell and
angstrom 2018 startup logs.
> Add mx5-pt conf and build scripts

- recipes-kernel/linux/linux-mobility-imx_4.19.bb
Modify Makefile and Kconfig files in kernel to include STM32 driver in
kernel. Driver is added to kernel zImage.
The method is to checkout the mxm5-cocpu git repo in an extra-drivers
folder at top level in kernel tree. We then create symbolic links in
drivers/platform to have the kernel Kbuild system pick up the sources.
> MX-5: Add Co-CPU driver to kernel recipe

- recipes-bsp/u-boot/files/mx6/0001-Add-mx5-defconfig.patch
- recipes-bsp/u-boot/files/mx6/0003-Add-mx5-uboot-and-spl-implementation.patch
- recipes-bsp/u-boot/files/mx6/flashmx5.cmd
- recipes-bsp/u-boot/u-boot-hostmobility-flash-mx5.bb
Add a check from U-Boot to the CO-CPU that checks if the user has pushed
the reset button or otherwise set CO-CPU I2C register 2 to 1 to indicate that
the a re-programming from an image file shall be done. The check is done
in the bootcmd environmental variable.
If the MX5 shall be flashed, a script with the name flashmx5.scr(created
from flashmx5.cmd) is expected to be found on the first detected USB
flash memory. The script handles the flashing sequence by loading the
image file that shall be programmed on the eMMC of the MX5. The image
file shall have the name mx5-image.wic.gz
To trigger an update:
* Place flashmx5.cmd and mx5-image.wic.gz on an USB memory.
* Insert the USB memory into the MX-5
* Press the reset button
* Alternatively, use i2ctransfer -y 2 w3@0x46 0 2 1 and restart
> MX5: Add Flash from USB functionality

- conf/machine/mx5-pt.conf
- recipes-hostmobility/packagegroups/packagegroup-hostmobility-commercial-mx5.bb
Replace "MX-5" with "MX-V" in machine description but keep
"mx5-pt" as the machine name used in the build system.
In addition, set the hostname to "mxv-pt". This overrides the machine
name.
> Rename MX-5 into MX-V and change hostname to mxv-pt

- conf/machine/include/mx4-tegra3-base.inc
add EXTRA_IMAGECMD:ext3 = "-b 4096 -g 32768 "
to allow faster reflashing of the system when
using t30_hmupdate.img file in /boot on target machine.
> T30: Set ext3 partition arguments -b 4096 -g 32768

- recipes-kernel/linux/linux-variscite/0001-add-hmx-device-tree.patch
- recipes-kernel/linux/linux-variscite/0018-power-reset-gpio-poweroff-add-force-mode.patch
- recipes-kernel/linux/linux-variscite_%.bbappend
Add gpio-poweroff handler that pulls GPIO4_IO19 to completely turn off the board. NOTE: another pm_power_off handler is already registered and gpio-poweroff.c needs to be patched to overwrite it.
The power-off functions seems to be the handled by the psci driver that turns off the CPU but we pull the gpio and turn off the power instead.
Reference:
https://www.thegoodpenguin.co.uk/blog/an-overview-of-psci/
A question is should we allow power-off when KL15/start-signal is on.
> Add gpio-poweroff handler that pulls GPIO4_IO19

- recipes-kernel/linux/linux-variscite/0001-add-hmx-device-tree.patch
- recipes-kernel/linux/linux-variscite/0022-gpio-keys-make-disabled-keys-not-wake-system.patch
- recipes-kernel/linux/linux-variscite_%.bbappend
* Update device tree so keys can be disabled
* Modify driver so wake-up only occurs if a key has NOT been disabled.
> HMX: patch gpio-keys: make disabled keys not wake system

- recipes-kernel/linux/linux-hostmobility-vf/mx4-c61/0001-add-device-tree-for-c61-v61.patch
V61 keeps default names where c61 has some renamed to nc which is not connected.
> C61:V61: Fix Gpio names for co-cpu

- conf/machine/include/hmx-base.conf
NetworkManager is installed due to
PREFERRED_CONNECTIVITY_MANAGER_PACKAGES
being set in meta-variscite-bsp/conf/machine/variscite.inc Set this to nothing instead.
> hmx:Do not install networkmanager

- dynamic-layers/recipes-kernel/linux/linux-variscite/0020-HMX-backport-m_can-from-linux-can-next.patch
- dynamic-layers/recipes-kernel/linux/linux-variscite/0021-HMX-Add-suspend-to-backported-m_can-driver.patch
- dynamic-layers/recipes-kernel/linux/linux-variscite/0026-HMX-m_can-do-not-init-registers-until-bus-on.patch
- dynamic-layers/recipes-kernel/linux/linux-variscite/0027-tcan4x5x-add-direct-register-read-debug.patch
- dynamic-layers/recipes-kernel/linux/linux-variscite/0028-tcan4x4-stop-queue-first-in-transmit-to-avoid-race.patch
- dynamic-layers/recipes-kernel/linux/linux-variscite/0029-tcan4x5x-remove-msg-lost-netdev_err-print.patch
- dynamic-layers/recipes-kernel/linux/linux-variscite_%.bbappend
tcan4x5x driver backported from linux-can-next repo with added suspend, register init wait to prevent errorframes and race condition fix.
Some cosmetic debug prints and commented out code to be cleaned up
> Hmx backport tcan4x5x from linux can6 2

- dynamic-layers/recipes-kernel/linux/linux-variscite/0001-add-hmx-device-tree.patch
The device tree node of the second root USB hub is at &usb_dwc3_1. Move USB nodes here for device nodes to be found for the USB-hubs below. They needed for the  ethernet MAC addresses coming from U-Boot to be found by the  smsc95xx driver.
> HMX: Correct MAC addresses on eth0 and eth1

- conf/machine/include/hmx-base.conf
- recipes-core/systemd/systemd/0001-units-add-dependencies-to-avoid-conflict-between-con.patch
- recipes-core/systemd/systemd/0002-units-disable-systemd-networkd-wait-online-if-Networ.patch
- recipes-core/systemd/systemd/imx.conf
- recipes-core/systemd/systemd_%.bbappend
Variscite wants to use NetworkManager, we want to use systemd-networkd. Since the meta-variscite-bsp/recipes-core/systemd/systemd_%.bbappend removes networkd, we cannot re-append it so we copy the bbappend recipe to our layer and BBMASK the variscite version.
(Tried forcevariable PACKAGECONFIG but that does not seem to work with kirstone, maybe another syntax?)
> HMX:Put back systemd-networkd

- dynamic-layers/recipes-bsp/u-boot/u-boot-variscite/0003-HMX-custom-imx8mp_var_dart.patch
- recipes-bsp/flash-script/flash-script/imx8mp-var-dart-hmx1/flash.cmd
- recipes-bsp/hm-autostart/hm-autostart/autostart.sh
Using set_RGB_ID to first probe for all known Ids and if it is found set it to RGB_I2C_ID
(will be used in flash.cmd and linux autostart.sh) and save enviorment.
set_RGB_ID will on success found this RGB. set to
i2c dev 1; echo RGB ID:$RGB_I2C_ID; for later prints when bsp_bootcmd is running.
> HMx uboot: fix auto detect right rgb LED ID

- dynamic-layers/recipes-kernel/linux/linux-variscite/0001-add-hmx-device-tree.patch
* Point the ethernet2 alias to eth0_obd and ethernet3 to eth1_rj45. This way, we only need two MAC addresses from our EEPROM in the Host Mobility OUI(04:1B:94) range and we keep the Variscite addresses(F8-DC-7A) from the SOM EEPROM.
NOTE: EEPROM needs to be changed all units so eth2addr and eth3addr gets the first and second Host Mobility addresses
> hmx:dt alias ethernet2/3 as eth0_obd/eth1_rj45

- recipes-modem/quectel/files/modem_firmware_update_helper.sh
- Simplify the platform system check
- Support mx4-c61 variants such as mx4-c61-rio
> recipes-modem: quectel: firmware update helper: Support c61 variants

- conf/machine/include/mx4-tegra3-base.inc
when we removed mx4-extra we forgot to add  kernel-modules to MACHINE_EXTRA_RDEPENDS. Tested and it works in kirkstone poky
> mx4-T30: fix kernel modules to image

- dynamic-layers/recipes-kernel/linux/linux-variscite/0001-add-hmx-device-tree.patch
- Fix red/green inconsistency
- Rename gsm (associated with 2G) -> wwan (broader category)
- Update copyright years
> hmx: dt: gpio-leds: Rename identifiers for consistency and clarity

- recipes-kernel/kernel-modules/kernel-module-pic_git.bb
- recipes-kernel/linux/linux-hostmobility_mainline-6.1.bb
mx4_pic: version magic
'6.1.26 SMP preempt mod_unload ARMv7 p2v8 '
should be
'6.1.26-r0 SMP preempt mod_unload ARMv7 p2v8 '
There is a -r0 in the expected vermagic.
It comes from the linux kernel local version
argument. Remove LOCALVERSION in kernel
mainline recipe.
Add depends on virtual/kernel in module recipe.
> T30(fr): Fix mx4_pic driver bad version magic

- recipes-bsp/hm-autostart/hm-autostart/autostart.sh
Add verdin-am62-hmm to
- automatic start of host watchdog
- hostname to ${MACHINE}-SERIAL
> autostart: add hmm-specific instructions

- dynamic-layers/recipes-kernel/linux/linux-variscite/0038-USB-modem-EM05GV2.patch
- dynamic-layers/recipes-kernel/linux/linux-variscite/0039-Add-additional-USB-EM05V2-driver-support.patch
- dynamic-layers/recipes-kernel/linux/linux-variscite_%.bbappend
We now support 0x030e(V2) and older version 0x030a(V1) This patches are from linux kernel 6.1.53 and can be removed on when we update the kernel.
> HMX: support new EM05(V2) USB connection id

- recipes-kernel/kernel-modules/gpio-overlay-hmm_1.0.bb
add support for multiple enable analog in 20ma messurment pins. https://github.com/hostmobility/hm-commercial/commit/586c7beeced8701cb6c272a167459f830a1da7ed
> hmm: update gpio overlay driver

- recipes-kernel/linux/linux-hostmobility-vf_4.19.bb
- recipes-kernel/linux/linux-hostmobility.inc
- recipes-kernel/linux/linux-hostmobility_mainline-4.19.bb
- recipes-kernel/linux/linux-hostmobility_mainline-6.1.bb
- Change the license name from GPLv2 to GPL-2.0-only. It fixes the following build warning:
"QA Issue: Recipe LICENSE includes obsolete licenses GPLv2 [obsolete-license]"
- Fix incorrect license for linux-hostmobility_mainline-6.1.b (Linux is not redistributable as GPL-3.0-or-later)
> recipes-kernel: Adjust Linux license

- recipes-kernel/kernel-modules/gpio-modem-controller_2.0.bb
fix so MODEM_ENABLE_ON is 1 on hmm. for mxv use version 1 of this controller. Still the driver is installed in linux kernel repo for the mxv so it currently not using the gpio-modem-controller recipe.
> hmm: fix modem_controller v.2

- recipes-core/systemd/systemd/verdin-am62-hmm/wait-for-network.service
- recipes-core/systemd/systemd_%.bbappend
Add delay to postpone network.target since the hmm have an observed behviour of making the flag appear to early in the systemd boot process, this can cause the system to reboot itself if the system is loaded with heavy computional services during startup since the watchdog timer will run out.
> network.target fix
